# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160923_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=models.ImageField(default=0, upload_to=''), null=True, upload_to='', width_field=models.ImageField(default=0, upload_to='')),
        ),
    ]
