# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 10:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
